apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-inno
  labels:
    app: user-service-inno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-inno
  template:
    metadata:
      labels:
        app: user-service-inno
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres-user 5432; do echo waiting for postgres; sleep 2; done;']
        - name: wait-for-redis
          image: busybox
          command: ['sh', '-c', 'until nc -z redis 6379; do echo waiting for redis; sleep 2; done;']
      containers:
        - name: user-service-inno
          image: direwait/userservise-inno:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_NAME
              value: "userdb"
            - name: DB_HOST
              value: "postgres-user"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: REDIS_HOST
              value: "redis"

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 10

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 10